# Generated by Django 4.1 on 2022-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='class',
            name='letter_id',
            field=models.CharField(max_length=2, verbose_name='Буквенное обозначение'),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год обучения'),
        ),
    ]
