# Generated by Django 4.1 on 2022-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workload',
            field=models.PositiveSmallIntegerField(verbose_name='Нагрузка'),
        ),
    ]
