# Generated by Django 4.1 on 2022-09-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_workload_workload'),
        ('lessons', '0004_c'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c',
            new_name='ScheduleItem',
        ),
    ]
