# Generated by Django 4.1 on 2022-09-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_c_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='date',
            field=models.DateField(default="2020-01-01", verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
