# Generated by Django 4.1 on 2022-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_scheduleitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='date',
            field=models.DateField(default='2022-1-1', verbose_name='Дата'),
        ),
    ]
