# Generated by Django 4.1 on 2022-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_scheduleitem_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'verbose_name': 'Ячейка рассписания', 'verbose_name_plural': 'Ячейки рассписания'},
        ),
    ]
